### ISSUE TITLE
How to use pretrained model in coco detection

### ISSUE THREAD

**Issue by ianpundar** [facebookresearch/ConvNeXt-V2#12]
I modify the code of convnextv1 in mmdet, including adding GRN and deleting LayerScale.
I use the checkpoint "convnextv2_base_1k_224_fcmae.pt" to initialize model weights, and I also use "remap_checkpoint_keys" to reshape grn affine parameters and biases.
No error was reported when loading checkpoint, but after 1 epoch, I only get about 1m AP in coco.

**Comment by zhengye1995** [comment]
Hi, I meet the same issue when using  'convnextv2_nano_22k_384_ema.pt' in detection and segmentation tasks.
I follow the implementation details of convnext in mmdet and mmseg.

**Comment by RangiLyu** [comment]
@ianpundar @zhengye1995 
Here is an example of using convnext-v2 in MMDetection.
https://github.com/open-mmlab/mmdetection/pull/9619
Since the official training is not released yet, the accuracy cannot be aligned yet.

**Comment by zhengye1995** [comment]
@RangiLyu Thanks! I will try it.

**Comment by ianpundar** [comment]
@RangiLyu Thanks! I have tried it. I keep v2 the same config as v1. There is only 1mAP in the first epoch, and the rise is very fast. I'm guessing this might be normal? But in the end, v2 is only a little better than v1.
