### ISSUE TITLE
Inplementation mismatch with the paper

### ISSUE THREAD

**Issue by NonBee98** [facebookresearch/ConvNeXt-V2#14]
Great work! I try to use the GRN in another model, but when I check the source code, I find one mismatch. In papaer, equation 2 uses the  sum of gx as the denominator, but in this implementation, GRN module uses the mean operator. Don't whether this will affect the final result.

**Comment by s9xie** [comment]
There’s not really a mismatch. We have a footnote near eqn 2 that explains the additional constant to accommodate different network depth. We will clarify in the revision.
