### ISSUE TITLE
parameter shape mismatch in GRN

### ISSUE THREAD

**Issue by MrWaterZhou** [facebookresearch/ConvNeXt-V2#19]
https://github.com/facebookresearch/ConvNeXt-V2/blob/3608f67cc1dae164790c5d0aead7bf2d73d9719b/models/utils.py#L16-L23

https://github.com/facebookresearch/ConvNeXt-V2/blob/3608f67cc1dae164790c5d0aead7bf2d73d9719b/models/utils.py#L105-L112

Both shape should be ok, but may cause trouble in finetuning (GRN parameter cannot be loaded)

**Comment by shwoo93** [comment]
During fine-tuning, the following helper function remaps the weights.

https://github.com/facebookresearch/ConvNeXt-V2/blob/3608f67cc1dae164790c5d0aead7bf2d73d9719b/utils.py#L545
