### ISSUE TITLE
ImageNet-1K Benchmarks (Trained from scratch) 

### ISSUE THREAD

**Issue by ahatamiz** [facebookresearch/ConvNeXt-V2#21]
Nice work ! based on the benchmarks in the paper and also this repository, it seems that all ImageNet-1K benchmarks use self-supervised pre-trained checkpoints. If this is the case, I would like to ask if authors can provide ImageNet-1K benchmarks for models that are trained from scratch. This enables direct comparison to other models which don't use self-supervised pre-training which constitute a large fraction of the literature.

**Comment by shwoo93** [comment]
The from-scratch ConvNeXt V2 training results are summarized in the main paper Table 14.
