### ISSUE TITLE
Question on decoder resolution

### ISSUE THREAD

**Issue by cmsflash** [facebookresearch/ConvNeXt-V2#25]
https://github.com/facebookresearch/ConvNeXt-V2/blob/2553895753323c6fe0b2bf390683f5ea358a42b9/models/fcmae.py#L186

The above function implements the MAE training logic. If I understand correctly, `x` after `self.forward_encoder()` should have been downsampled 4 times after patchification. See https://github.com/facebookresearch/ConvNeXt-V2/blob/2553895753323c6fe0b2bf390683f5ea358a42b9/models/convnextv2_sparse.py#L122

Then, `pred` should have the same spatial dimension as `x`. `self.proj` and `self.decoder` preserve spatial dimensions. `self.pred` only recovers the in-patch dimensions, preserving the number of patches.

Overall, `pred` should have `4^4` times fewer patches than `self.patchify(imgs)`. However, they are directly put in a subtraction in

https://github.com/facebookresearch/ConvNeXt-V2/blob/2553895753323c6fe0b2bf390683f5ea358a42b9/models/fcmae.py#L164

What am I missing here?

Essentially, how do you recovered the downsampled number of patches if you decode from the lowest-resolution encodings?

**Comment by Mogul5306** [comment]
I have the same question.

**Comment by cmsflash** [comment]
This line defines `self.pred`, which expands the dimensionality to `self.patch_size ** 2 * 3`:
https://github.com/facebookresearch/ConvNeXt-V2/blob/d7cc26f7dccc6ba941e76609359d670ed213cb73/models/fcmae.py#L64-L67
Then, this line `patchify()`s `target()`, effectively aligning the dimensions with `pred`:
https://github.com/facebookresearch/ConvNeXt-V2/blob/d7cc26f7dccc6ba941e76609359d670ed213cb73/models/fcmae.py#L175
