### ISSUE TITLE
cannot import name 'MinkowskiDepthwiseConvolution' from 'MinkowskiEngine'.

### ISSUE THREAD

**Issue by XiaoyuAIPro** [facebookresearch/ConvNeXt-V2#35]
Hello, great work.
In Install.md it says: (Note: we have implemented a customized CUDA kernel for depth-wise convolutions, which the original MinkowskiEngine does not support.)
but in the code, it still has `from MinkowskiEngine import MinkowskiDepthwiseConvolution`
So what do you mean by that?
I found that there is MinkowskiChannelwiseConvolution.py in MinkowskiEngine, is it possible to replace MinkowskiDepthwiseConvolution in the code with MinkowskiChannelwiseConvolution, or some another solution? I hope I can get your answer, thanks!

Translated with www.DeepL.com/Translator (free version)

**Comment by XiaoyuAIPro** [comment]
Thanks, I have found it in readme.
[shwoo93](https://github.com/shwoo93)
/[MinkowskiEngine](https://github.com/shwoo93/MinkowskiEngine)

**Comment by Chole0529** [comment]
Hi ，I'm sorry to bother you. But，may I ask，can you please tell me how you solved this problem, I didn't find the solution to the problem in question inside the link you provided, thanks.

**Comment by BoyOfChu** [comment]
> Hi ，I'm sorry to bother you. But，may I ask，can you please tell me how you solved this problem, I didn't find the solution to the problem in question inside the link you provided, thanks.

https://github.com/shwoo93/MinkowskiEngine/tree/bbc30ef581ea6deb505976b663f5fc2358a83749
This is version of  MinkowskiEngine with MinkowskiDepthwiseConvolution. You install the MinkowskiEngine via this version.

**Comment by XiaoyuAIPro** [comment]
> Hi ，I'm sorry to bother you. But，may I ask，can you please tell me how you solved this problem, I didn't find the solution to the problem in question inside the link you provided, thanks.

There tell you how to install it  https://github.com/shwoo93/MinkowskiEngine/tree/bbc30ef581ea6deb505976b663f5fc2358a83749?tab=readme-ov-file#pip

**Comment by XiaoyuAIPro** [comment]
About install MinkowskiEngine, check : https://github.com/shwoo93/MinkowskiEngine/tree/bbc30ef581ea6deb505976b663f5fc2358a83749?tab=readme-ov-file#pip. There had told you how to install~










At 2024-03-29 14:05:54, "BoyOfChu" ***@***.***> wrote:

Hi ，I'm sorry to bother you. But，may I ask，can you please tell me how you solved this problem, I didn't find the solution to the problem in question inside the link you provided, thanks.

https://github.com/shwoo93/MinkowskiEngine/tree/bbc30ef581ea6deb505976b663f5fc2358a83749
This is version of MinkowskiEngine with MinkowskiDepthwiseConvolution. You install the MinkowskiEngine via this version.
