### ISSUE TITLE
Reason for double mask in Jax implementation?

### ISSUE THREAD

**Issue by sebastian-sz** [facebookresearch/ConvNeXt-V2#45]
While reading the [TRAINING.md](https://github.com/facebookresearch/ConvNeXt-V2/blob/main/TRAINING.md#implementing-fcmae-with-masked-convolution-in-jax) I noticed that the mask is applied twice in the Jax's `Block` implementation:

```python
@nn.compact
  def __call__(self, inputs, mask=None):
    if mask is not None:
      x = inputs * (1. - mask)
    x = DepthwiseConv2D((7, 7), name='dwconv')(x)
    if mask is not None: # The binary masking is numerically identical to sparse conv.
      x = x * (1.- mask)
    (...)
```

What benefit does this bring? Couldn't the mask be only applied to the output with the same result? Aka something like:

```python
@nn.compact
  def __call__(self, inputs, mask=None):
    x = DepthwiseConv2D((7, 7), name='dwconv')(x)
    if mask is not None: # The binary masking is numerically identical to sparse conv.
      x = x * (1.- mask)
```

I would greatly appreciate some hint.

**Comment by powermano** [comment]
The first mask is to ensure that the pixels dropped by the mask will not affect the convolution, and the second mask is to ensure that the part of the mask is still 0 after conv

**Comment by sebastian-sz** [comment]
@powermano thank you for the answer. Could you explain how the input pixels could affect the convolution if we didn't apply the first mask?
