### ISSUE TITLE
The reconstruction images have a lot of noise

### ISSUE THREAD

**Issue by powermano** [facebookresearch/ConvNeXt-V2#48]
The following image is the result of epoch=69.
![test_epoch_69](https://user-images.githubusercontent.com/24365567/237036439-e6496b2e-4c6d-49ef-938a-efcc5f8b2fb6.png)

The reconstruction of unmasked part have lots of noise, is this a normal phenomenon？

And I have found a strange problem.  If i replace the first conv in the stem with MinkowskiDepthwiseConvolution, the training loss will quickly drop to 0.  I can't understand why this is happening.

**Comment by Mogul5306** [comment]
How to reconstuct the image. Could you provide the code?

**Comment by powermano** [comment]
> How to reconstuct the image. Could you provide the code?

same as MAE.  https://github.com/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb

**Comment by Mogul5306** [comment]
I encountered the same question. Have you solved this problem?  The reconstruction images have a lot of noise. 
![image](https://github.com/facebookresearch/ConvNeXt-V2/assets/44825764/e4fa5633-36ad-4403-b057-732933566f64)

**Comment by powermano** [comment]
> I encountered the same question. Have you solved this problem? The reconstruction images have a lot of noise. ![image](https://user-images.githubusercontent.com/44825764/241258524-e4fa5633-36ad-4403-b057-732933566f64.png)

I did not encounter the problem,  maybe you can check you visualization codes.

**Comment by powermano** [comment]
I using another self-supervised learning for CNN, SparK(https://github.com/keyu-tian/SparK), and the reconstruction of unmasked part have lots of noise too. 
![recon_res](https://github.com/facebookresearch/ConvNeXt-V2/assets/24365567/ba7c0498-2da0-416a-a7d8-99c73b184823)

Maybe the reason is due to loss fuction, as the reconstruction loss is only applied to the part of the mask, and the part without the mask is not constrained

**Comment by supertx** [comment]
Hi @powermano,

I saw your preview and noticed you're working on facial reconstruction. It seems you've made some progress. I've been working on a similar project but haven't achieved the desired results. Could you share any insights or experiences🙏🏻?

Thanks!
