### ISSUE TITLE
Efficiency comparison between dense conv + binary masking and sparse conv

### ISSUE THREAD

**Issue by rayleizhu** [facebookresearch/ConvNeXt-V2#5]
What's the efficiency comparison between 

1. dense conv + binary masking
2. sparse conv with MinkowskiEngine

Specifically, I'd like to know the following statistics **in the pertaining stage** for the two variants:

* hardware: [e.g.  single 8 V100 node]
* Batch time: [e.g. 0.8s (sparse) / 0.9s (dense) ]

As far as I know, sparse operators are much less efficient in modern hardware. According to [Nvidia blog](https://developer.nvidia.com/blog/accelerating-matrix-multiplication-with-block-sparse-format-and-nvidia-tensor-cores/):

> Even though sparse linear algebra allows representing huge matrices very efficiently, **it typically does not provide competitive performance compared to dense counterparts in cases when sparsity is below 95%**. This is due to irregular computation and scattered memory accesses. In fact, many of the linear algebra applications that benefit from sparsity have over 99% sparsity in their matrices.

Even a highly optimized block-sparse kernel **with a strict assumption on the sparse pattern still requires 40%~50% sparsity** to counteract the hardware inefficiency. Hence, as far as I'm concerned, a 60% mask rate (i.e. 60% sparsity) is not enough to accelerate the pertaining with sparse convolution, if it is not slower than dense convolution + binary masking.

**Comment by shwoo93** [comment]
Yes, we are aware of this issue and provided the comparisons in the supplementary material.
