### ISSUE TITLE
Hello, I found some bugs

### ISSUE THREAD

**Issue by wuyx517** [facebookresearch/ConvNeXt-V2#6]
In the subproject MinkowskiEngine, the three c++ codes src/depthwise_convolution_gpu.cu, depthwise_convolution_kernel.cu, depthwise_convolution_kernel.cuh are commented with # at the beginning, which will cause compilation failure.
![image](https://user-images.githubusercontent.com/40740068/210490628-d79504fc-5314-4c6d-868e-7a96396d7beb.png)

**Comment by shwoo93** [comment]
Thanks for noting this. They are fixed now.
